name: Update Air Quality Data
run-name: Updating the air quality data 🚀
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "10 * * * *"
permissions:
  contents: write
jobs:
  Update-Data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node updateData.mjs
      - run: |
          git config --global user.name 'Powiecze Bot'
          git config --global user.email 'krzksz@users.noreply.github.com'
          git commit -am "Update air quality data"
          git push
